spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/home_projects
spring.datasource.username=dev_user
spring.datasource.password=Kira14052010
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ==========================================
# AI Agent Settings (Ollama)
# ==========================================
# Базовый URL, где крутится Ollama на вашем Mac Mini
spring.ai.ollama.base-url=http://localhost:11434

# Указываем модель, которую вы только что скачали
spring.ai.ollama.chat.options.model=qwen2.5:1.5b

# Выставляем низкую температуру (0.3), чтобы агент отвечал стабильно и не выдумывал лишнего
spring.ai.ollama.chat.options.temperature=0.3
